version: '3'
services:
  mongodb:
    image: mongo:6.0.2
    volumes:
      - .docker/dbdata:/data/db    
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=cash-machine

   